---
title: "Resources"
---

### Prerequisites
This workshop will utilize the R programmling language through the RStudio user interface. We will perform these activities on the RStudio Server, available through the [Posit Cloud](https://posit.cloud/) platform.
-   *Posit Cloud account*: You should have received access to Posit Cloud through a link to your email address. _If you did not receive this link, please contact @ for a new one._ Logging into the workspace, using this email address, will provide access to all course materials and allow for data analysis through RStudio Server on your internet browser.
-   *Laptop computer*: Please bring your own laptop with internet capability. Since the workshop will take place through Posit Cloud, the interface will be accessed through an internet browser. Google Chrome is recommended.

While the *Introduction to R programming* (Days 1-2) is is designed for all skill levels, having a basic understanding of R programming may enhance your learning experience. If you are new to these areas, consider reviewing one or a few of the following introductory materials prior to the workshop.

### During the course
Over the course of the workshop, teaching assistants ([TAs](authors.qmd)) will be working with small groups of attendees during the hands-on exercises. Feel free to direct your questions to the them, the instructors, or the Slack channel.

### After the course
-   *R*: In order to utilize the RStudio Desktop application from your laptop (and not through the browser), you will first need to install the latest version of R. [link]
-   *RStudio Desktop* can be downloaded here [link]. Note that this functions in the same manner as the RStudio Server by Posit Cloud, but utilizes the storage and compute of the laptop machine itself. Laptops vary in memory and storage space, which can dictate the speed and capability of data analysis, and this may result in slower processes with large datasets.

### Workshops and vignettes
-   [Single Cell Best Practices](https://www.sc-best-practices.org/preamble.html)
-   [RNA-seq Bioinformatics](https://rnabio.org/course/)
-   [Precision Medicine Bioinformatics](https://pmbio.org/)
-   [Orchestrating Single-Cell Analysis with Bioconductor](https://bioconductor.org/books/release/OSCA/)
